[[configuring-new-orb-fragment-processing]]
== Configuring the New ORB Fragment Processing

The objective of this functionality is to improve the concurrency mechanism with a new implementation using the
Lock API. The benefits of using this mechanism instead of the default one (based on synchronized blocks of code)
are the following:

* Fine-Grained control: We are doing explicit locking and unlocking, this is more precise and efficient than
the implementation with synchronized blocks.
* Use of conditions variables: This allows threads to wait for certain conditions to be met before proceeding.
* Multiple Object locking: lock can be shared among multiple class instances, allowing you to manage synchronization
across this instance more flexible.

NOTE: The Fragment processing happens when a big message is processed by the ORB. If the ORB message exceeds the default size of 1024 bytes, then the internal fragmentation of the message starts.

To configure the new functionality use the following properties:

.New ORB Fragment Processing Properties
|===
|Property |Description

| `com.sun.corba.ee.protocol.enableNewFragmentProcess`
| This property will enable the new fragment processing. By default, this property is set as `false` to use the older implementation based on synchronized blocks of code.

| `com.sun.corba.ee.protocol.newFragmentEmptyConditionTimeout`
| You can use this property to change the wait timeout for fragments of a request. By default, the timeout is 10000 milliseconds. This property only takes effect if the `com.sun.corba.ee.protocol.enableNewFragmentProcess` is enabled. The unit for this property is milliseconds.

|===