= Release notes - Payara Platform Enterprise 6.21.0

== Supported APIs and Applications

* Jakarta EE 10
* Jakarta EE 10 Applications
* MicroProfile 6.1


== Bug Fixes

* [FISH-9875] Fix inconsistent deployment of a web app when the instances are shared on multiple groups

* [FISH-10036] Fix ClassCastException when deserializing instances of `jakarta.validation.ConstraintViolation`

* [FISH-10136] Fix PayaraMicro throws NPE at `org.glassfish.web.loader.WebappClassLoader.clearBeanResolver(WebappClassLoader.java:2677)` when booting

* [FISH-10146] Fix NullPointerException when running the `add-instance-to-deployment-group` command


== Component Upgrades

* [FISH-9165] Update Jakarta XML Binding API to 4.0.2

* [FISH-10128] Payara: Bump jline.version from 3.27.0 to 3.27.1

* [FISH-10159] Payara: Bump `com.nimbusds:nimbus-jose-jwt` from 9.41.2 to 9.47

* [FISH-10189] Payara: Bump `io.projectreactor:reactor-core` from 3.6.10 to 3.7.0

* [FISH-10192] Payara: Bump `commons-io:commons-io` from 2.17.0 to 2.18.0

* [FISH-10231] Bump `org.eclipse.persistence:org.eclipse.persistence.asm` from 9.7.0 to 9.7.1

* [FISH-10232] Bump `org.apache.aries.spifly:org.apache.aries.spifly.dynamic.bundle` from 1.3.6 to 1.3.7

* [FISH-10237] Payara: Bump `org.jetbrains.kotlin:kotlin-stdlib` from 2.0.21 to 2.1.0

* [FISH-10278] Payara: Bump `com.fasterxml.jackson:jackson-bom` from 2.18.1 to 2.18.2
